name: prodigy
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - icu=78.2
  - libffi=3.5.2
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libsqlite=3.51.2
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.1
  - packaging=26.0
  - pip=26.0.1
  - python=3.10.14
  - readline=8.3
  - setuptools=82.0.0
  - tk=8.6.13
  - wheel=0.46.3
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - pip:
      - annotated-types==0.7.0
      - attrdict==2.0.1
      - attrs==25.4.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - filelock==3.20.3
      - fsspec==2026.2.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - hf-xet==1.2.0
      - huggingface-hub==0.14.1
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - littleutils==0.2.4
      - lmdb==1.7.5
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - msgpack==1.1.2
      - networkx==3.4.2
      - nltk==3.9.2
      - numpy==1.26.4
      - ogb==1.3.6
      - outdated==0.2.2
      - pandas==2.3.3
      - pillow==12.1.0
      - platformdirs==4.5.1
      - protobuf==6.33.5
      - psutil==7.2.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - ray==2.53.0
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - rpds-py==0.30.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentence-transformers==2.2.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.52.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.13.3
      - torch==2.0.1
      - torch-geometric==2.3.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - tqdm==4.67.3
      - traitlets==5.14.3
      - transformers==4.29.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - wandb==0.24.2
prefix: /Users/philipp/miniconda3/envs/prodigy
